name: fontra

services:
  nginx:
    image: nginx:1-alpine
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/my-site.crt
      - ./nginx/nginx-selfsigned.key:/etc/ssl/private/my-site.key
    ports:
      - 18089:443
    depends_on:
      - server
    networks:
      - fontra_network

  fontra:
    restart: always
    build:
        dockerfile: Dockerfile.frontend
    environment:
      TZ: Asia/Kuala_Lumpur
    ports:
      - "8000:8000"
    networks:
      - fontra_network

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      TZ: Asia/Kuala_Lumpur
    volumes:
      - ./robocjk-settings:/var/lib/conf/env_settings
      - ./rcjk-src:/root/robocjk/temp/
      - ./git-ssh:/root/.ssh
    depends_on:
      - db
    networks:
      - fontra_network

#   db:
#     image: postgres:16
#     restart: always
#     # set shared memory limit when using docker-compose
#     shm_size: 128mb
#     # or set shared memory limit when deploy via swarm stack
#     #volumes:
#     #  - type: tmpfs
#     #    target: /dev/shm
#     #    tmpfs:
#     #      size: 134217728 # 128*2^20 bytes = 128Mb
#     environment:
#         POSTGRES_DB: robocjk
#         POSTGRES_USER: robocjk
#         POSTGRES_PASSWORD: ""
#     volumes:
#       - "./pgdata:/var/lib/postgresql/data"
#     command: -c 'max_connections=200'
#     ports:
#       - 5432:5432
#     networks:
#       - fontra_network

  register:
    build:
      context: ./fontra-register
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: robocjk
      DATABASE_USER: robocjk
      DATABASE_PASSWORD: ""
      INVITATION_KEY: ""
    ports:
      - "5000:5000"
    networks:
      - fontra_network

  db:
    image: mariadb:lts
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_DATABASE: robocjk
      MARIADB_USER: robocjk
      MARIADB_PASSWORD: ""
    volumes:
      - ./db.cnf:/etc/mysql/conf.d/db.cnf
      - robocjk-mysql:/var/lib/mysql
    ports:
        - 3306:3306
    networks:
        - fontra_network
    ulimits:
        nofile:
            soft: 20000
            hard: 40000

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
#     networks:
#       - fontra_network

volumes:
    robocjk-postgres:
    robocjk-mysql:

networks:
  fontra_network:
    name: fontra_network
    driver: bridge
